apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./auth.yaml
  - ./client.yaml
  - ./tickets.yaml
  - ./orders.yaml
  - ./payments.yaml
  - ./ingress.yaml
  - ./mongo.yaml
  - ./nats.yaml